### ISSUE TITLE
rules in help

### ISSUE THREAD

**Issue by carlbordum** [Akuli/curses-klondike#1]
I suggest printing the rules of the game in the help menu. Alternatively, an "r" keybinding for a rules page, or a "second" page in the help menu for rules.

**Comment by Akuli** [comment]
i think i could make a longer rule page and pipe the help to less or `$PAGER` or something, if i don't want to implement scrolling stuff, not sure about how curses would work with that

i don't think the rules will fit on one 80x24 screenful, even if they're in a separate "r" keybinding

would you write the rules if i do the code that displays them?

**Comment by carlbordum** [comment]
I will not write the rules. There are many versions of this game and you know exactly what you implemented. You can find something online and reference that.

**Comment by Akuli** [comment]
This is implemented now on master. Let me know what you think.

**Comment by carlbordum** [comment]
This is nice. I wish more programs had curses interfaces :)
